### ISSUE TITLE
CBAM yolo.py 修改

### ISSUE THREAD

**Issue by achel-x** [coderhukai/yolov5-5.x-annotations#3]
您好，感谢您对U版代码的详细注释。关于CBAM的使用，我有一些问题，如果您方便解答的话，我将十分感激
1、我希望在yolov3中插入CBAM，就正常的在yolo head前插入，但是通过yaml我没有办法非常清晰的观察yolo的结构，且照你的Yolov5s中插入，插入如下，不知是否正确
![image](https://user-images.githubusercontent.com/67953243/144804554-a79047af-2db5-4120-ba00-9cf7fe6d0ef9.png)
2、在yolo.py部分增加CBAM代码处，您的代码给出了SE的部分，但是抱歉我的水平有限，无法举一反三写出CBAM对应的操作，希望如果方便的话，也请赐教
![image](https://user-images.githubusercontent.com/67953243/144804761-60fa2ab2-cacd-4845-a70a-9f6bc88f6e99.png)
3、您是否有跑过加入CBAM后的yolo，对mAP大约有多大的提升

**Comment by HuKai97** [comment]
![image](https://user-images.githubusercontent.com/68494594/144837849-b72d69c5-dc79-4385-9a64-cfcc039823ca.png)

**Comment by HuKai97** [comment]
这个trick还是要看具体任务啊，我自己的任务上还是SE还用点

**Comment by achel-x** [comment]
你好，我使用您的CBAM的代码，在yolo.py里尝试打印model
但是报错是ChannelAttention的对象没有调用，
![image](https://user-images.githubusercontent.com/67953243/145022622-ae86121e-fe23-46aa-8eb0-673df4024af1.png)

我插入的位置大约在backbone的后面，模型选用的是yolov3，配置文件如下
![image](https://user-images.githubusercontent.com/67953243/145022260-2d332926-39be-42c7-af15-30fa2e13cf75.png)
common.py 和 yolo.py的修改和你一致，请问如何修改

**Comment by SCAU-HuKai** [comment]
![image](https://user-images.githubusercontent.com/68494594/145313943-e86cbeed-52cf-4004-80f5-42ea41a3ffe9.png)

**Comment by HuKai97** [comment]
检查报语句中的变量名和函数名是否重用

**Comment by achel-x** [comment]
额，我换了在网上找到的另一份CBAM的代码解决的这个问题，好像是输入变量的不一样
