### ISSUE TITLE
关于您在注释版本内绘制的YOLOv5s结构图，有问题想请教您，如果方便的话希望可以回复下

### ISSUE THREAD

**Issue by Zzzz1zzz** [coderhukai/yolov5-5.x-annotations#5]
![yolov5s](https://user-images.githubusercontent.com/92008678/170978010-3956c604-97a1-41de-95bd-e83bc985d567.png)

比如说backbone内spp结构输出【1,512,20,20】，1具体指代哪一个量的输出？512是否为channel输出？

**Comment by HuKai97** [comment]
1：batch_size
512：channel
20：w h

**Comment by Zzzz1zzz** [comment]
谢谢大佬

**Comment by Zzzz1zzz** [comment]
![GitHubQ](https://user-images.githubusercontent.com/92008678/170996780-ddadf727-3075-4f45-b0bd-ab4fa6cb5990.jpg)
再想问下，图片里面的C处：为何经过C3块时 channel 会减少，其他的（如ABD处）就没有变化？
第二个问题是 Detcect接收的channel 全部都是75，是您自己改进还是v5s版本设置就是75？

**Comment by Zzzz1zzz** [comment]
或者说：Focus出来应该是【1,64,320,320】吧？

**Comment by HuKai97** [comment]
这个v5作者网络就是这么设计的，应该问他，我个人理解是为了和上面的输出feature map作concat吧（一般concat都是channel相同   很少看到不相同的concat）

**Comment by Zzzz1zzz** [comment]
好的，万分感谢

**Comment by HuKai97** [comment]
第二个问题，我好像图画的有点问题，那3个conv k=1，s=1其实就是head，应该把它画进去的

**Comment by HuKai97** [comment]
不好意思，造成歧义了，那个75就是head的输出channel，（xywh+c+voc 20classes）x3

**Comment by Zzzz1zzz** [comment]
> 不好意思，造成歧义了，那个75就是head的输出channel，（xywh+c+voc 20classes）x3

明白了，感谢感谢

**Comment by Zzzz1zzz** [comment]
<img width="744" alt="1653962405(1)" src="https://user-images.githubusercontent.com/92008678/171078054-88974ba9-6599-4fab-bbb8-febfcb1a0f31.png">
<img width="590" alt="1653962514(1)" src="https://user-images.githubusercontent.com/92008678/171078305-f072605b-739c-4de5-9896-58587ccc6d23.png">

大佬您好，看了您在common.py中加入的几种注意力机制，yolo.py里也进行了相应修改---比如上图加了CBAM，但是yolov5s.yaml文件的backbone仍然未改动，是已经实验了注意力机制然后特意恢复到初始backbone的吗？还是说另有原因？

**Comment by HuKai97** [comment]
只是在代码上写好了，都没做实验，这个做的话太麻烦了，得先训练预训练权重，还要测试到底加载哪个位置比较好，因为我的卡不够，就没做什么实验。这个仓库主要是解释下YOLOv5各个部分的代码

**Comment by Zzzz1zzz** [comment]
> 只是在代码上写好了，都没做实验，这个做的话太麻烦了，得先训练预训练权重，还要测试到底加载哪个位置比较好，因为我的卡不够，就没做什么实验。这个仓库主要是解释下YOLOv5各个部分的代码
那如果我在yolov5（未加入CBAM版本）训练了一个自己数据集的权重，现在将权重拿来用在 您这个加了CBAM机制的版本上可行吗？

**Comment by HuKai97** [comment]
不行，要用公开大型数据集训练yolov5+cbam模型，得到预训练权重，再用这个预训练权重训练自己的数据集，这样结果才准确

**Comment by Zzzz1zzz** [comment]
那要这样的话，自己的卡确实是跑不动啊。明白了，十分感谢您。我在CSDN上私信您了，方便看下吗？  名字XuanX
