### ISSUE TITLE
加载数据集问题

### ISSUE THREAD

**Issue by cheeenzq** [coderhukai/yolov5-5.x-annotations#6]
博主你好，请问我想要在yaml文件中改网络格式，想要输入的是两个模态的数据（红外和可见光模态）。现在需要有两个输入的数据集要被读到，博主可以给一些建议吗，有偿，十分感谢了。

**Comment by HuKai97** [comment]
多模态任务我也了解的不多。我的想法：1、可以试试把两种数据融合之后输入网络，2、先把可见光图片输入backbone前向推理后，再把红外数据融合再输入head。

**Comment by HuKai97** [comment]
不一定对，可以看看多模态相关论文

**Comment by cheeenzq** [comment]
好的，非常感谢。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Hu Kai ***@***.***&gt;
发送时间: 2022年12月4日 17:15
收件人: HuKai97/yolov5-5.x-annotations ***@***.***&gt;
抄送: cheeenzq ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[HuKai97/yolov5-5.x-annotations] 加载数据集问题 (Issue #6)





 
不一定对，可以看看多模态相关论文
